name: Deploy to S3

on:
  push:
    branches:
      - master # Trigger on pushes to the master branch
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Or your preferred Node.js version

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the React app
      - name: Build the React app
        run: npm run build

      # 5. Deploy to S3
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} # Your S3 bucket name
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS Access Key ID
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS Secret Access Key
          AWS_REGION: ${{ secrets.AWS_REGION }} # AWS region

